harnessApiVersion: '1.0'
type: INFRA_DEFINITION
cloudProviderType: KUBERNETES_CLUSTER
deploymentType: HELM
infrastructure:
- type: DIRECT_KUBERNETES
  cloudProviderName: labs-k8s-cluster
  namespace: prodcution
  releaseName: ${infra.kubernetes.infraId}
