version: 2.1

orbs:
  maven: circleci/maven@0.0.12      

workflows:
  maven_test:
    jobs:
      working_directory: ~/springboot-helm-chart/demoweb
      steps:
        - checkout

        # run tests!
        - run: mvn package
